version: '3.7'
services:
  mongo:
    networks:
      - lambda-network
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: tagclouds
    ports:
      - 27017:27017
  
  frontend:
    networks:
      - lambda-network
    image: node:20.0.0-alpine3.17
    volumes:
      - ./frontend/:/app
    ports: 
      - 4200:4200
    working_dir: /app
    command: npm run docker

  backend:
    networks:
      - lambda-network
    image: openjdk:11
    volumes:
      - ./LambdaTagCloud/:/app
    working_dir: /app
    ports:
      - 8080:8080
    command: ./mvnw spring-boot:run

networks:
  lambda-network:
    driver: host